apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env
data:
  DB_HOST: localhost
  DB_PORT: "5432"
  NODE_ENV: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-file
data:
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
