apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cnpg.io/nodeSerial: "1"
    cnpg.io/operatorVersion: 1.27.0
    cnpg.io/pvcStatus: ready
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: nfs.csi.k8s.io
    volume.kubernetes.io/storage-provisioner: nfs.csi.k8s.io
  creationTimestamp: "2025-09-18T19:50:43Z"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    cnpg.io/cluster: postgres
    cnpg.io/instanceName: postgres-1
    cnpg.io/instanceRole: primary
    cnpg.io/pvcRole: PG_DATA
    role: primary
  name: postgres-1
  namespace: jellyfin
  ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      controller: true
      kind: Cluster
      name: postgres
      uid: 90afed56-3b1e-4c9c-92df-1cc4252ad04b
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-csi-main
  volumeMode: Filesystem
  volumeName: pvc-7eda306d-228c-4c58-85d6-454cdb01f522
